# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-09 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathswizard', '0002_auto_20171121_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='focus',
            field=models.CharField(choices=[('Addition', 'Addition'), ('Multiplication', 'Multiplication'), ('Subtraction', 'Subtraction')], default='Addition', max_length=100),
        ),
    ]
