# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-09 22:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathswizard', '0003_studentprofile_focus'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='difficulty',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Beginner', max_length=100),
        ),
    ]
