# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-20 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathswizard', '0021_auto_20180319_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='Dislikes',
            field=models.CharField(choices=[('Addition', 'Addition'), ('Multiplication', 'Multiplication'), ('Subtraction', 'Subtraction'), ('N/A', 'N/A')], default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='Likes',
            field=models.CharField(choices=[('Addition', 'Addition'), ('Multiplication', 'Multiplication'), ('Subtraction', 'Subtraction'), ('N/A', 'N/A')], default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='focus',
            field=models.CharField(choices=[('Addition', 'Addition'), ('Multiplication', 'Multiplication'), ('Subtraction', 'Subtraction'), ('N/A', 'N/A')], default='Addition', max_length=100),
        ),
    ]
