# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-27 14:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mathswizard', '0026_auto_20180323_1350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentprofile',
            old_name='Dislikes',
            new_name='dislikes',
        ),
        migrations.RenameField(
            model_name='studentprofile',
            old_name='Likes',
            new_name='likes',
        ),
    ]
