# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-30 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathswizard', '0029_auto_20180328_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='cof',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='level',
            field=models.CharField(default='1', max_length=100),
        ),
    ]
