# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-03 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathswizard', '0031_studentprofile_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='skipped',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
