# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-13 00:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathswizard', '0031_auto_20180412_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='completed',
            field=models.IntegerField(default='0'),
        ),
    ]
