# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-03 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathswizard', '0034_auto_20180403_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='levelProg',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
