# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-03 20:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mathswizard', '0035_studentprofile_levelprog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentprofile',
            old_name='levelProg',
            new_name='levelprog',
        ),
    ]
