# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-11 01:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathswizard', '0036_auto_20180403_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='cof',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='completed',
            field=models.IntegerField(default='1'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='level',
            field=models.IntegerField(default='1'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='levelprog',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='skipped',
            field=models.IntegerField(default='0'),
        ),
    ]
